### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by meridius** [dockette/devstack#1]
Hi,

could you please state some examples in the readme on how to get a web application up and running (e.g. Nette sandbox)? I tried but could not get it working. My top success was to get a blank directory listing from Apache when loading one of stated domains in the browser.

Here is my setup:

- changed content of `~/projects/docker-devstack/devstack` is
    `COMPOSE=docker-compose.yml`  
    other is the same
- `devstack` command in my bin
- `~/projects/sandbox/docker-compose.yml` copied from yours and changed the following (other is the same)
    ```
  data:
      image: busybox

      volumes:
        - ./src:/srv
    ```
- `~/projects/sandbox/src/` is the directory with Nette sandbox
- I get the mentioned result when running the `devstack up` in the directory with project `~/projects/sandbox/docker-compose.yml`

Thank you in advance.

**Comment by f3l1x** [comment]
Thank you for feedback. I will try to write something.

-----

Hot idea: Have you define absolute paths? Without `~`?

**Comment by f3l1x** [comment]
@meridius I've just updated this devstack and also README, is it better now? Can we close it?

**Comment by meridius** [comment]
I think so, thank you.
