### ISSUE TITLE
Sloupce a řádky v bash

### ISSUE THREAD

**Issue by landsman** [dockette/devstack#10]
Neřešil jsi tento problém?
Když vstoupím do bash containeru, tak se nebindují sloupce dle šířky okna terminálu. Tzn pak při středně dlouhém commandu přepisuji začátek řádku, jako kdybych použil nějaký insert. Je to otravné.

**Test - moje OS:**
```
$ tput cols
175
$ tput lines
46
```
**Container:**
```
$ devstack gu php72
dfx@7ef16fc8ede1:/srv$ tput cols
80
dfx@7ef16fc8ede1:/srv$ tput lines
24
```

Děje se mi to pokud mám otevřených více terminálů v tabech. Pokud pozavírám ostatní a nechám pouze jeden s exec do containeru, nabindují se správné env variables.

**Screenshoty:**
![screenshot from 2018-07-15 11-57-37](https://user-images.githubusercontent.com/3184228/42732736-c74b35ce-8826-11e8-827d-e62838a8e7f8.png)
![screenshot from 2018-07-15 12-00-59](https://user-images.githubusercontent.com/3184228/42732738-c768959c-8826-11e8-85bf-a9d6f033efdc.png)

**Comment by f3l1x** [comment]
Mam pocit, ze jsem nekde videl reseni. Myslim, ze staci nejaka ENV promena. Ale tedka nevim.

**Comment by landsman** [comment]
Ted jsem si ho taky vsiml.
Do docker-compose pridat: `COLUMNS: 80` k php service.
Poslu PR.

**Comment by f3l1x** [comment]
ping @landsman

**Comment by f3l1x** [comment]
Closing due to neactivity. Feel free to open it again.
