### ISSUE TITLE
upgrade docker-compose na v3

### ISSUE THREAD

**Issue by freezysko** [dockette/devstack#14]
@f3l1x nezvazujes upgrade docker-compose na v3?
umoznilo by to pouzivat premenne v definicii portov
nevyhodou je ze by bolo treba prerobit volumes_from lebo v3 neumoznuje zdielanie volume zo services ale len z volumes definovanych na najvyssej urovni compose file

**Comment by f3l1x** [comment]
Ahoj. Urcite by to bylo fajn. Pripravis PR?

**Comment by f3l1x** [comment]
Closing due to neactivity.
