### ISSUE TITLE
Readme: wrong PHP 5.6 hosts URL

### ISSUE THREAD

**Issue by Crempa** [dockette/devstack#2]
I think local URLs mentioned in readme (hosts section) for PHP 5 versions are wrong right? It should be `local.dev56` instead of `local.dev5`.

**Comment by f3l1x** [comment]
You're right. I'll fix it.

**Comment by f3l1x** [comment]
Fixed via - https://github.com/dockette/devstack/commit/130cc8c937e3082abb821c14323ff09a776df2c8
