### ISSUE TITLE
Adminer maybe not working

### ISSUE THREAD

**Issue by Crempa** [dockette/devstack#3]
Hi, everything works except Adminer. This is not big deal for me, but maybe its bug and you are interested in :-)

I'm not sure how this should work, but nothing is running on `localhost:8000`.  I'm not sure if something is exposed to this port, see my `devstack list` result.

```
        Name                       Command                State                      Ports                   
------------------------------------------------------------------------------------------------------------
devstack_adminer_1      /bin/sh -c /usr/bin/php -S ...   Exit 127                                            
devstack_apache_1       apache2ctl -D FOREGROUND         Up         0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp 
devstack_data_1         sh                               Exit 0                                              
devstack_mariadb_1      docker-entrypoint.sh mysqld      Up         3306/tcp                                 
devstack_nodejs_1       /bin/sh -c /bin/bash             Up                                                  
devstack_php56_1        php-fpm5.6 -F                    Up                                                  
devstack_php7_1         php-fpm7.1 -F                    Up                                                  
devstack_postgresql_1   docker-entrypoint.sh postgres    Up         0.0.0.0:5432->5432/tcp                   
devstack_userdirs_1     sh                               Exit 0  
```

PS: Maybe you should mention something about Adminer and where its running in README (or just link to dockette/adminer repository should be ok) 

PS2: check last version of Adminer (you mention v4.2.5 in README, actual is v4.3.1)

THX for great work anyway ;)

**Comment by Crempa** [comment]
maybe this startup log entry can help 
`adminer_1     | /bin/sh: /usr/bin/php: not found`

**Comment by f3l1x** [comment]
Thank you for the bugreport. I've already fix that. 👍 

https://github.com/dockette/adminer/commit/3fc54b770f60228b94180cd3673f108bf7844bb4
