### ISSUE TITLE
HSTS preload list - .dev domain

### ISSUE THREAD

**Issue by kralmichal** [dockette/devstack#8]
Hi,

new versions of chrome has modified HSTS preload list which forces all .dev domains to be on https. That means that local.dev won't work anymore. 

Source:
https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

**Comment by f3l1x** [comment]
Thanks. We should rename it to .local?

**Comment by kralmichal** [comment]
There is mention in the article about https://tools.ietf.org/html/draft-west-let-localhost-be-localhost-06 . It proposes that all *.localhost would automatically translate to 127.0.0.1, without /etc/hosts or dnsmasq workarounds. So why don't go .localhost? On the other hand it is quite long.

**Comment by f3l1x** [comment]
Well, we should pick some. Any hints? Still *.localhost remains? :-)

**Comment by kralmichal** [comment]
I still prefer using *.localhost as you don't have to modify system's host file.

**Comment by f3l1x** [comment]
Localhost looks good to me. Could you please send a PR?

**Comment by kralmichal** [comment]
Sure. I will get to it around this weekend.

**Comment by f3l1x** [comment]
Closing due to neactivity. Feel free to open it.
